<div class="container m-5 p-3">
    <form action="../userdashboard/addwebhook" method="post">
        <h2 class='text-center '>Add Webhook's</h2>
        <label for="Webhook Name(URL)">Webhook Name(URL)</label>
        <input type="text" class="form-control" name='url' placeholder="Enter Url">
        <br>
        <label for="event name">Event Name</label>
        <input type="text" class="form-control" name='event' placeholder="Enter Event">
        <br>
        <input type="submit" value="Add" class='btn btn-primary'>
    </form>
</div>

