<div class='div text-center  p-3' style="width:600px;margin-left:300px;border:2px solid lightgreen">
<form action="../robot/robotadd" method="post">
    <h1>Add Robot's</h1>
    <label>Robot Id</label>
    <input type="number" name="id" class="form-control">
    <br>
    <label>Robot Name</label>
    <input type="text" name="name" class="form-control">
    <br>
    <label>Robot Quantity</label>
    <input type="number" name="qty" class="form-control">
    <br>
    <label>Robot Price</label>
    <input type="number" name="price" class="form-control">
    <br>
    <label>Robot Description</label>
    <input type="text" name="desc" class="form-control">
    <br><br>
    <input type="submit" value="submit" class='btn btn-primary'>
    <a href="../robot/robotview" class="btn btn-primary">View Robots</a>
</form>
</div>
